### ISSUE TITLE
SDK isn't Require-able

### ISSUE THREAD

**Issue by Akamaozu** [AJFunk/nasa-sdk#21]
`var nasa = require('nasa-sdk');`

![image](https://cloud.githubusercontent.com/assets/1587024/26146971/007a759a-3ac0-11e7-980e-93a4aab4b29f.png)

**Comment by AJFunk** [comment]
Is this error being thrown when you try to use it in a browser?

**Comment by AJFunk** [comment]
This should be fixed now, please update to version 1.1.9

**Comment by Akamaozu** [comment]
No problem.

For the record I was using it in plain ol' Node.js.

**Comment by AJFunk** [comment]
Ah, well this should fix it! Thanks for reporting the issue :)

**Comment by Akamaozu** [comment]
Fixed indeed :)

![image](https://cloud.githubusercontent.com/assets/1587024/26170162/6a38f97c-3b0e-11e7-953e-fd4401501082.png)

Thanks for the quick fix.
