### ISSUE TITLE
Validate status parameter for eonet module

### ISSUE THREAD

**Issue by sspann** [AJFunk/nasa-sdk#7]
- [x] Create and implement a `validateStatus` function in `eonet.js`

**Comment by AJFunk** [comment]
only add it to `util.js` if it's going to be used in other modules (I'm guessing it's not?). Otherwise, add the function to `eonet.js`

**Comment by sspann** [comment]
Agree. As of right now this function will only be used in `eonet.js`. I'll implement it there.
